import Transition from "./components/Transition";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Learning BarbaJS",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body data-barba="wrapper">
				<div
					id="transition"
					className="absolute z-10 w-full h-svh top-0 left-0 pointer-events-none bg-blue-400 scale-y-0"
				/>
				<Transition />
				{children}
			</body>
		</html>
	);
}
